### ISSUE TITLE
Bundled Postgres should be started on non-default port

### ISSUE THREAD

**Issue by roosmaa** [RiseVision/rise-build#3]
Currently, if the machine already has a postgres running the bundled postgres fails to start up but to it attempting to bind to the same ports. The best fix would be to use a separate, unique port for the bundled postgres to minimize collisions with other services.

**Comment by roosmaa** [comment]
The required changes to the `includes/db.sh` to support custom DB_PORT from the network config files:

```patch
--- db.sh-old   2018-04-10 12:53:54.709856289 +0100
+++ db.sh-new   2018-04-10 12:53:26.803033671 +0100
@@ -12,6 +12,8 @@
     export DB_LOG_FILE="${LOGS_DIR}/pgsql.log"
     export DB_SNAPSHOT="blockchain.db.gz"
     export DB_DOWNLOAD=Y
+
+    export PGPORT=$DB_PORT
 }
 
 db_pid() {
@@ -84,6 +86,7 @@
             db_reset
             pg_ctl initdb -D "$DB_DATA" >> "$SH_LOG_FILE" 2>&1
             sleep 5
+            sed -i "s/^#port = 5432/port = $DB_PORT/" $DB_DATA/postgresql.conf
             db_start
         fi
     fi
```

**Comment by vekexasia** [comment]
Would you please create a pull request ? @roosmaa :)
